#ifndef EXCEPTION_IMPLANTS_H
#define EXCEPTION_IMPLANTS_H

#include <exception>
#include <string>
#include "implants_export.h"

class IMPLANTS_EXPORT ImplantsException : public std::exception
{
    std::string msg_;
public:
    ImplantsException(const std::string& msg) : msg_(msg) {}

    virtual const char* what() const noexcept override
    {
        return msg_.c_str();
    }
};

enum IMPLANTS_EXPORT ImplantExceptionCode
{
    ALREADY_INITIALIZED_KNEE = 1,
    ALREADY_INITIALIZED_BALANCE,
    ALREADY_INITIALIZED_FEMUR_IMPLANT,
    ALREADY_INITIALIZED_FEMUR_IMPLANT_MATCH,
    ALREADY_INITIALIZED_HIP_FEMUR_STEM_IMPLANT,
    ALREADY_INITIALIZED_HIP_FEMUR_STEM_IMPLANT_MATCH,
    ALREADY_INITIALIZED_HIP_PELVIS,
    ALREADY_INITIALIZED_HIP_PELVIS_CUT_IMPLANT,
    ALREADY_INITIALIZED_HIP_PELVIS_CUT_IMPLANT_MATCH,
    ALREADY_INITIALIZED_PATELLA,
    ALREADY_INITIALIZED_PATELLA_IMPLANT,
    ALREADY_INITIALIZED_PATELLA_IMPLANT_MATCH,
    ALREADY_INITIALIZED_PATELLA_IMPLANT_MATCH_INFO,
    ALREADY_INITIALIZED_PLANE,
    ALREADY_INITIALIZED_TIBIA_IMPLANT,
    ALREADY_INITIALIZED_TIBIA_IMPLANT_MATCH,
    FAILED_TRANSFORMATION_MATCH_BY_CONDYLE,
    FAILED_TRANSFORMATION_MATCH_BY_CORTEX,
    CAN_NOT_DEFINE_BORDER_BETWEEN_LATERAL_AND_MEDIAL_CONDYLES,
    CAN_NOT_DEFINE_DIFFERENT_BORDER_FOR_LATERAL_AND_MEDIAL_SIDE,
    CAN_NOT_DEFINE_DIFFERENT_BORDER_FOR_INFERIOR_AND_SUPERIOR_SIDE,
    CAN_NOT_DETERMINE_CONVEX_HULL_ON_LATERAL_SIDE,
    CAN_NOT_DETERMINE_CONVEX_HULL_ON_MEDIAL_SIDE,
    CAN_NOT_DETERMINE_MAIN_POINTS_IN_CONVEX_HULL_ON_LATERAL_SIDE,
    CAN_NOT_DETERMINE_MAIN_POINTS_IN_CONVEX_HULL_ON_MEDIAL_SIDE,
    CAN_NOT_DETERMINE_CONVEX_HULL_ON_PATELLA_CUT_PLANE,
    CAN_NOT_DETERMINE_CONVEX_HULL_ON_TIBIA_CUT_PLANE,
    CAN_NOT_DETECT_REFERENCE_POINT_AT_INFERIOR_CONTOUR_CORNER,
    CAN_NOT_DETECT_REFERENCE_POINT_AT_SUPERIOR_CONTOUR_CORNER,
    FAILED_COMPUTING_CENTER_OF_ROTATION_ON_HIP_PELVIS,
    CAN_NOT_DETERMINE_FEMUR_AXIS_ON_HIP_PELVIS,
    CAN_NOT_DETERMINE_MIDPOINT_OF_AP_AXIS_ON_TIBIA_IMPLANT_MATCH,
    CAN_NOT_DETERMINE_MIDPOINT_OF_AP_AXIS_ON_TIBIA,
    CAN_NOT_DETERMINE_ANATOMIC_AXIS_ON_TIBIA,
    CAN_NOT_DETERMINE_DISTAL_FEMUR_CONDYLES_POINTS,
    CHECK_LANDMARKS_CAN_NOT_DETERMINE_BEGIN_POINT_OF_KNEE_GROOVE,
    CHECK_LANDMARKS_CAN_NOT_DETERMINE_WHITESIDE_LINE,
    CAN_NOT_DETERMINE_PATELLA_GROOVE,
    CAN_NOT_DETERMINE_DIMENSIONS_OF_TIBIA_IMPLANT,
    LINE_DIRECT_VECTOR_CAN_NOT_BE_ZERO,
    CAN_NOT_DETERMINE_PERPENDICULAR_LINE_TO_LINE,
    CAN_NOT_FIT_PATELLA_FRONTAL_PLANE,
    CAN_NOT_DETERMINE_PATELLA_DISTAL_POSTERIOR_POINT,
    NOT_ENOUGH_POINTS_ON_CUT_PLANE,
    POINTS_TO_DEFINE_PLANE_CAN_NOT_BE_EQUAL,
    POINTS_TO_DEFINE_PLANE_CAN_NOT_BE_COLLINEAR,
    PLANE_NORMAL_VECTOR_CAN_NOT_BE_ZERO,
    CAN_NOT_DETERMINE_PERPENDICULAR_PLANE_TO_PLANE,
    CAN_NOT_DETERMINE_INTERCEPTION_LINE_TO_PLANE,
    CAN_NOT_DETERMINE_HIGHEST_POINTS_ON_BOTH_SIDE_OF_PCL,
    NOT_ENOUGH_POINTS_ON_PCL_BORDER,
    CAN_NOT_FIT_POLY_ON_PCL_BORDER,
	CAN_NOT_DETERMINE_CONVEX_HULL,
	CAN_NOT_DETERMINE_CONVEX_HULL_CORNERS
};

#endif
